
stages:
  - build

android_build:
  image: openjdk:11-jdk
  stage: build
  script:
    - apt-get update && apt-get install -y wget unzip
    - wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
    - unzip commandlinetools-linux-7583922_latest.zip -d $HOME/android-sdk
    - export ANDROID_HOME=$HOME/android-sdk
    - export PATH=$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH
    - yes | sdkmanager --licenses
    - sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-30"
    - chmod +x ./gradlew
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/apk/debug/app-debug.apk
